In [3]:
import numpy as np

In [4]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[0,0,0,1]]).T
X.shape ,Y.shape

((4, 2), (4, 1))

In [5]:
def sig(z):
    return 1/(1+np.exp(-z))

In [6]:
# no hidden layer weights
weights=2*np.random.random((2,1))-1
bias=2*np.random.random(1)-1
weights,bias

(array([[ 0.39070187],
        [ 0.46789846]]), array([-0.02756427]))

In [7]:
# forward propogation with no hidden layer 
output0=X
output=sig(np.dot(output0,weights)+bias)
output

array([[ 0.49310937],
       [ 0.60833866],
       [ 0.58979974],
       [ 0.69657395]])

In [10]:
wh=2*np.random.random((2,2))-1
bh=2*np.random.random((1,2))-1
wo=2*np.random.random((2,1))-1
bo=np.random.random((1,1))-1

In [11]:
output0=X
outputHidden=sig(np.dot(output0,wh)+bh)
output=sig(np.dot(outputHidden,wo)+bo)
output

array([[ 0.6123021 ],
       [ 0.63451856],
       [ 0.58439855],
       [ 0.60900261]])