In [64]:
import numpy as np

In [65]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[0,0,0,1]]).T
X.shape ,Y.shape

((4, 2), (4, 1))

In [66]:
def sig(z):
    return 1/(1+np.exp(-z))

In [67]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

In [71]:
# no hidden layer weights
weights=2*np.random.random((2,1))-1
bias=2*np.random.random(1)-1
lr=0.1
weights,bias

(array([[-0.81162686],
        [-0.26456828]]), array([ 0.13215566]))

In [69]:
# forward propogation with no hidden layer
for iter in range(10000):
    output0=X
    output=sig(np.dot(output0,weights)+bias)
    first_term=output-Y
    input_for_last_layer=np.dot(output0,weights)+bias
    second_term=derivativeSig(input_for_last_layer)
    first_two=first_term*second_term

    changes=np.array([[0.0],[0.0]])
    for i in range(2):
        for j in range(4):
            changes[i][0]+=first_two[j][0]*output[j][0]
    weights=weights-lr*changes 
    bias_change=0.0        
    for j in range(4):
            bias_change+=first_two[j][0]*1        
    bias=bias-lr*bias_change
output=sig(np.dot(X,weights)+bias)  
weights,bias,output

(array([[ 6.31756008],
        [ 6.3128834 ]]), array([-9.43707101]), array([[  7.97071934e-05],
        [  4.21204929e-02],
        [  4.23095843e-02],
        [  9.60584109e-01]]))

In [72]:
# forward propogation with no hidden layer
for iter in range(10000):
    output0=X
    output=sig(np.dot(output0,weights)+bias)
    first_term=output-Y
    input_for_last_layer=np.dot(output0,weights)+bias
    second_term=derivativeSig(input_for_last_layer)
    first_two=first_term*second_term
    changes=np.dot(output0.T,first_two)
    weights=weights-lr*changes 
    bias_change=np.sum(first_two)        
    bias=bias-lr*bias_change
output=sig(np.dot(X,weights)+bias)  
weights,bias,output

(array([[ 5.47023473],
        [ 5.47023474]]), array([-8.29808516]), array([[  2.48931172e-04],
        [  5.58376154e-02],
        [  5.58376150e-02],
        [  9.33540048e-01]]))